-- PAYTRACK LOAN MANAGEMENT SYSTEM DATABASE

CREATE TABLE "users" ( -- usuarios
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "paternal_surname" varchar, 
  "maternal_surname" varchar, 
  "national_id" varchar, -- cedula/curp
  "phone" varchar,
  "address" varchar, -- direccion
  "salary" decimal, -- salario
  "role" varchar, -- rol
  "status" varchar DEFAULT 'active', -- estado
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "clients" ( -- clientes
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "paternal_surname" varchar, 
  "maternal_surname" varchar, 
  "occupation" varchar, -- ocupacion
  "national_id" varchar, -- cedula/curp
  "address" varchar, -- direccion
  "phone" varchar,
  "birth_date" date, -- fecha_nacimiento
  "status" varchar, -- estado
  "notes" text, -- notas
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "loans" ( -- prestamos
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "amount" decimal, -- monto
  "payment_count" int, -- numero_pagos
  "interest_rate" decimal, -- tasa_interes
  "payment_start_date" date, -- fecha_inicio_pagos
  "late_interest" decimal, -- interes_moratorio
  "status" varchar, -- estado
  "authorizer_id" int, -- id_autorizador
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "payments" ( -- pagos
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "responsible_id" int, -- id_responsable
  "amount" decimal, -- monto
  "interest_amount" decimal, -- monto_interes
  "payment_method" varchar, -- metodo_pago
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "expenses" ( -- gastos
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsible_id" int, -- id_responsable
  "expense_date" date, -- fecha_gasto
  "payment_method" varchar, -- metodo_pago
  "description" text, -- descripcion
  "amount" decimal, -- monto
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "suppliers" ( -- proveedores
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "phone" varchar,
  "contact" varchar, -- contacto
  "description" text, -- descripcion
  "folio" varchar, -- folio
  "address" varchar, -- direccion
  "supplier_type" varchar, -- tipo_proveedor
  "status" varchar DEFAULT 'active', -- estado
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "files" ( -- archivos
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "file_name" varchar, -- nombre_archivo
  "file_path" varchar, -- ruta_archivo
  "client_id" int,
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "collection_routes" ( -- rutas_cobranza
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int, -- id_empleado
  "loan_id" int,
  "assignment_date" date, -- fecha_asignacion
  "status" varchar, -- estado
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "reports" ( -- reportes
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_name" varchar, -- nombre_reporte
  "report_type" varchar, -- tipo_reporte
  "generator_user_id" int, -- id_usuario_generador
  "generation_date" timestamp -- fecha_generacion
);

CREATE TABLE "client_financial_history" ( -- historial_financiero_cliente
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "current_debt" decimal, -- deuda_actual
  "active_loans_count" int, -- cantidad_prestamos_activos
  "payment_delays_count" int, -- cantidad_retrasos_pago
  "average_delay_days" int, -- promedio_dias_retraso
  "total_loaned_amount" decimal, -- monto_total_prestado
  "created_at" timestamp, 
  "updated_at" timestamp, 
  "deleted_at" timestamp 
);

CREATE TABLE "daily_cutoff" ( -- corte_diario
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date, -- fecha
  "responsible_id" int, -- id_responsable
  "total_income" decimal, -- ingresos_totales
  "total_expenses" decimal, -- gastos_totales
  "profit" decimal, -- ganancia
  "created_at" timestamp 
);

-- FOREIGN KEY CONSTRAINTS
ALTER TABLE "loans" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
ALTER TABLE "loans" ADD FOREIGN KEY ("authorizer_id") REFERENCES "users" ("id");
ALTER TABLE "payments" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
ALTER TABLE "payments" ADD FOREIGN KEY ("responsible_id") REFERENCES "users" ("id");
ALTER TABLE "expenses" ADD FOREIGN KEY ("responsible_id") REFERENCES "users" ("id");
ALTER TABLE "files" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
ALTER TABLE "collection_routes" ADD FOREIGN KEY ("employee_id") REFERENCES "users" ("id");
ALTER TABLE "collection_routes" ADD FOREIGN KEY ("loan_id") REFERENCES "loans" ("id");
ALTER TABLE "reports" ADD FOREIGN KEY ("generator_user_id") REFERENCES "users" ("id");
ALTER TABLE "client_financial_history" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
ALTER TABLE "daily_cutoff" ADD FOREIGN KEY ("responsible_id") REFERENCES "users" ("id");