CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "apellido_paterno" varchar,
  "apellido_materno" varchar,
  "ine" varchar,
  "telefono" varchar,
  "direccion" varchar,
  "sueldo" decimal,
  "rol" varchar,
  "estado" varchar DEFAULT 'activo',
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "clientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "apellido_paterno" varchar,
  "apellido_materno" varchar,
  "ocupacion" varchar,
  "ine" varchar,
  "direccion" varchar,
  "telefono" varchar,
  "fecha_nacimiento" date,
  "estado" varchar,
  "notas" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "prestamos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "monto" decimal,
  "cantidad_pagos" int,
  "tasa_interes" decimal,
  "fecha_inicio_pago" date,
  "interes_por_atraso" decimal,
  "estado" varchar,
  "autorizador_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "pagos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "responsable_id" int,
  "monto" decimal,
  "monto_interes" decimal,
  "modo_pago" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "egresos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsable_id" int,
  "fecha_egreso" date,
  "modo_pago" varchar,
  "descripcion" text,
  "monto" decimal,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "proveedores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "telefono" varchar,
  "contacto" varchar,
  "descripcion" text,
  "folio" varchar,
  "direccion" varchar,
  "tipo_proveedor" varchar,
  "estado" varchar DEFAULT 'activo',
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "archivos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_archivo" varchar,
  "ruta_archivo" varchar,
  "cliente_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "rutas_cobro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empleado_id" int,
  "prestamo_id" int,
  "fecha_asignacion" date,
  "estado" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "reportes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_reporte" varchar,
  "tipo_reporte" varchar,
  "usuario_generador_id" int,
  "fecha_generacion" timestamp
);

CREATE TABLE "historial_financiero_cliente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "adeudo_actual" decimal,
  "cantidad_prestamos_activos" int,
  "cantidad_atrasos_pagos" int,
  "promedio_dias_atraso" int,
  "monto_total_prestado" decimal,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "corte_al_dia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "responsable_id" int,
  "total_ingresos" decimal,
  "total_egresos" decimal,
  "utilidad" decimal,
  "created_at" timestamp
);

ALTER TABLE "prestamos" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "prestamos" ADD FOREIGN KEY ("autorizador_id") REFERENCES "usuarios" ("id");

ALTER TABLE "pagos" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "pagos" ADD FOREIGN KEY ("responsable_id") REFERENCES "usuarios" ("id");

ALTER TABLE "egresos" ADD FOREIGN KEY ("responsable_id") REFERENCES "usuarios" ("id");

ALTER TABLE "archivos" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "rutas_cobro" ADD FOREIGN KEY ("empleado_id") REFERENCES "usuarios" ("id");

ALTER TABLE "rutas_cobro" ADD FOREIGN KEY ("prestamo_id") REFERENCES "prestamos" ("id");

ALTER TABLE "reportes" ADD FOREIGN KEY ("usuario_generador_id") REFERENCES "usuarios" ("id");

ALTER TABLE "historial_financiero_cliente" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "corte_al_dia" ADD FOREIGN KEY ("responsable_id") REFERENCES "usuarios" ("id");
